name = "forecastify-edu"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:cloudflare"
publish = "dist"

[build.upload]
format = "service-worker"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[site]
bucket = "./dist" 